training:
  epochs: 50
  batch_size: 128
  optimizer: SGD
  optimizer_kwargs:
    lr: 0.01
    momentum: 0.9
    weight_decay: 5.0e-04
  scheduler:
    type: cosine
model:
  arch: resnet18
data:
  dataset: CIFAR10
  data_dir: ./data