training:
  epochs: 1
  batch_size: 128
  optimizer: AdamW
  optimizer_kwargs:
    lr: 0.05
    betas: 
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 5.0e-04
  scheduler:
    type: cosine
model:
  arch: resnet18
data:
  dataset: CIFAR10
  data_dir: ./data